---

dhcpd_base_packages_map:
  'server':
    - 'dhcp-server'
  'relay':
    - 'dhcp-relay'
  'probe': []

dhcpd_services:
  'server':
    - 'dhcpd'
  'relay':
    - 'dhcpd'
  'probe': []

dhcpd_templates:
  - 'etc/dhcp/dhcpd.conf'

# vim: set ts=2 sw=2:
